### ISSUE TITLE
Use errors instead of panic?

### ISSUE THREAD

**Issue by andig** [eapache/queue#17]
Putting this up for discussion: public package api in go should rather use errors than panics. Would it make sense to have a 2.0 release implementing this approach?

**Comment by eapache** [comment]
This was a discussed in a PR a few years ago: https://github.com/eapache/queue/pull/6#issuecomment-118173496

**Comment by andig** [comment]
Good one, thank you!

**Comment by andig** [comment]
For sake of others, here's a smallish wrapper that will recover the panics as errors:

	type Q struct {
		*queue.Queue
	}

	func New() *Q {
		return &Q{ queue.New() }
	}

	func errorFromPanic(r interface{}) error {
		switch x := r.(type) {
		case string:
			return errors.New(x)
		case error:
			return x
		default:
			return errors.New("Unknown panic")
		}
	}

	func recoverWithError() error {
		if r := recover(); r != nil {
			return errorFromPanic(r)
		}
		return nil
	}
		
	func (q *Q) Peek() (res interface{}, err error) {
		defer func() {
			err = recoverWithError()
		}()
		
		return q.Queue.Peek(), nil
	}

	func (q *Q) Get(i int) (res interface{}, err error) {
		defer func() {
			err = recoverWithError()
		}()
		
		return q.Queue.Get(i), nil
	}

	func (q *Q) Remove() (res interface{}, err error) {
		defer func() {
			err = recoverWithError()
		}()
		
		return q.Queue.Remove(), nil
	}
